[profile.default]
solc_version = "0.8.30"
evm_version = "prague"

optimizer = true
optimizer_runs = 9_999_999

via_ir = true

remappings = [
  "@solady=lib/solady/",
  "@soledge=lib/soledge/",
  "@forge=lib/forge-std/src/"
]

[profile.via-ir]
via_ir = true

[fmt]
line_length = 100

[rpc_endpoints]
main = "https://eth-mainnet.public.blastapi.io"